# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [nerd, Bill,]
patreon: # Replace with a single Patreon username mouse36872
open_collective: # Replace with a single Open Collective username 
ko_fi: # Replace with a single Ko-fi username Doug
tidelift: # Replace with a single Tidelift platform-name/package-name mouse3687 , npm/babel npm install @babel/core @babel/register --save-dev
community_bridge: # Replace with a single Community Bridge project-name e.g.,bNA
liberapay: # Replace with a single Liberapay username mouse3687
issuehunt: # Replace with a single IssueHunt username mouse3687
otechie: # Replace with a single Otechie username mouse3687
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://Nike.com','https://nike.com,'https://iheartradio 'https://mypillow.com,']
